package roboticshours;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Alan
 */
public class AdminScreen extends JFrame implements TableModelListener{ 
    static JFrame mainScreen;
    private Account account; 
    DefaultTableModel dataModel; 
    Border defaultBorder;
    
    /** * Creates new form AdminScreen */ 
    public AdminScreen() { 
        initComponents();
        defaultBorder = firstNameField.getBorder();
        ArrayList<Entry> entries = new ArrayList<>(); 
        for(Account a : Run.getAccountList()){ 
            entries.addAll(a.getEntries());
        } 
        Object[][] data = new Object[entries.size()][5]; 
        for(int i = 0; i < entries.size(); i++){ 
            Entry e = entries.get(i);
            Calendar d = e.getDate(); 
            Calendar dm = e.getDateModified(); 
            data[i][0] = false; 
            data[i][1] = e.getUser().getAccountName().replace("+", " "); 
            data[i][2] = (d.get(Calendar.MONTH) + 1 + "/" + d.get(Calendar.DAY_OF_MONTH) + "/" + (d.get(Calendar.YEAR))); 
            data[i][3] = e.getHours(); 
            data[i][4] = (dm.get(Calendar.MONTH) + 1 + "/" + dm.get(Calendar.DAY_OF_MONTH) + "/" + (dm.get(Calendar.YEAR))); 
        }
        dataModel = new DefaultTableModel(data, new String [] {"", "Name", "Date", "Hours", "Date Modified"})
        {
            Class[] types = new Class [] {Boolean.class, String.class, String.class, Integer.class, String.class};
            boolean[] canEdit = new boolean [] {true, false, true, true, false};

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        dataModel.addTableModelListener(this); 
        entryTable.setModel(dataModel); 
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer(); 
        center.setHorizontalAlignment(JLabel.CENTER); 
        
        TableColumn column; 
        for (int i = 0; i < 5; i++) { 
            column = entryTable.getColumnModel().getColumn(i);
            if (i == 0) { 
                column.setPreferredWidth(5);
            }
            else if(i == 3){ 
                column.setPreferredWidth(10);
                column.setCellRenderer(center); } 
            else{ 
                column.setCellRenderer(center); 
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        greetingLabel = new javax.swing.JLabel();
        viewEditPanel = new javax.swing.JPanel();
        entryTableHeader = new javax.swing.JScrollPane();
        entryTable = new javax.swing.JTable();
        tableBackButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        newUserPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        confirmLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        newBackButton = new javax.swing.JButton();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField(){
            public void paste(){}
        };
        passwordConfirmField = new javax.swing.JPasswordField(){
            public void paste(){}
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        mainPanel.setLayout(new java.awt.CardLayout());

        startPanel.setPreferredSize(new java.awt.Dimension(338, 180));

        newButton.setActionCommand("Add New Account");
        newButton.setLabel("Add New Account");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        viewButton.setText("View/Edit Hours");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        greetingLabel.setText("Hello. What would you like to do?");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(greetingLabel)
                .addGap(88, 88, 88))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(greetingLabel)
                .addGap(55, 55, 55)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(viewButton))
                .addContainerGap())
        );

        mainPanel.add(startPanel, "startPanel");

        viewEditPanel.setPreferredSize(new java.awt.Dimension(338, 180));

        entryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Hours", "Date Modified"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        entryTable.getTableHeader().setReorderingAllowed(false);
        entryTableHeader.setViewportView(entryTable);
        if (entryTable.getColumnModel().getColumnCount() > 0) {
            entryTable.getColumnModel().getColumn(0).setHeaderValue("Date");
            entryTable.getColumnModel().getColumn(1).setHeaderValue("Hours");
            entryTable.getColumnModel().getColumn(2).setHeaderValue("Date Modified");
        }

        tableBackButton.setText("Back");
        tableBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableBackButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Selected");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewEditPanelLayout = new javax.swing.GroupLayout(viewEditPanel);
        viewEditPanel.setLayout(viewEditPanelLayout);
        viewEditPanelLayout.setHorizontalGroup(
            viewEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entryTableHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
            .addGroup(viewEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addContainerGap())
        );
        viewEditPanelLayout.setVerticalGroup(
            viewEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewEditPanelLayout.createSequentialGroup()
                .addComponent(entryTableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(viewEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableBackButton)
                    .addComponent(deleteButton))
                .addContainerGap())
        );

        mainPanel.add(viewEditPanel, "viewEditPanel");

        newUserPanel.setPreferredSize(new java.awt.Dimension(338, 180));

        firstNameLabel.setText("Preferred First Name:");

        lastNameLabel.setText("Last Name:");

        passwordLabel.setText("Password:");

        confirmLabel.setText("Confirm Password:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        newBackButton.setText("Back");
        newBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newUserPanelLayout = new javax.swing.GroupLayout(newUserPanel);
        newUserPanel.setLayout(newUserPanelLayout);
        newUserPanelLayout.setHorizontalGroup(
            newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserPanelLayout.createSequentialGroup()
                        .addComponent(newBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserPanelLayout.createSequentialGroup()
                        .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel))
                        .addGap(78, 78, 78)
                        .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(lastNameField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserPanelLayout.createSequentialGroup()
                        .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(confirmLabel))
                        .addGap(92, 92, 92)
                        .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField)
                            .addComponent(passwordConfirmField))))
                .addContainerGap())
        );
        newUserPanelLayout.setVerticalGroup(
            newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmLabel)
                    .addComponent(passwordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBackButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        mainPanel.add(newUserPanel, "newUserPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("mainFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        ((CardLayout)(mainPanel.getLayout())).show(mainPanel, "newUserPanel");
    }//GEN-LAST:event_newButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        for(int i = dataModel.getRowCount(); i > 0; i--){
            dataModel.setValueAt(false, i - 1, 0);
        }
        entryTable.clearSelection();
        ((CardLayout)(mainPanel.getLayout())).show(mainPanel, "viewEditPanel");
    }//GEN-LAST:event_viewButtonActionPerformed

    private void tableBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableBackButtonActionPerformed
        ((CardLayout)(mainPanel.getLayout())).show(mainPanel, "startPanel");
    }//GEN-LAST:event_tableBackButtonActionPerformed
    
    @Override
    public void tableChanged(TableModelEvent e){
        String name = (String) dataModel.getValueAt(e.getFirstRow(), 1);
        int offset = 0;
        for(Account a : Run.getAccountList()){
            if(name.equals(a.getAccountName().replace("+", " "))){
                account = a;
                break;
            }
            else{
                offset += a.getEntries().size();
            }
        }
        if(e.getColumn() == 2){
            String newDate = (String) dataModel.getValueAt(e.getFirstRow(), 2);
            if(parseDate(newDate)){
                Calendar date = new GregorianCalendar();
                String[] datePieces = newDate.split("/"); //Split the date into 3 pieces.
                if(datePieces[2].length() == 2){ //shorthand date form
                    datePieces[2] = ("" + date.get(Calendar.YEAR)).substring(0, 2) + datePieces[2]; //Getting the first two digits of the year. This method ensures working code after 2100
                }

                date.set(Integer.parseInt(datePieces[2]), Integer.parseInt(datePieces[0]) - 1, Integer.parseInt(datePieces[1]));
                account.getEntries().get(e.getFirstRow() - offset).setDate(date);
                
                dataModel.removeTableModelListener(this); //avoiding recursive fireTableStateChanged by deregistering the listener before editing cell value
                dataModel.setValueAt((date.get(Calendar.MONTH) + 1 + "/" + date.get(Calendar.DAY_OF_MONTH) + "/" + (date.get(Calendar.YEAR))), e.getFirstRow(), 2);
                dataModel.addTableModelListener(this); //Strangely, none of the other setValueAt calls seem to have this issue.
            }
            else{
                Calendar oldDate = account.getEntries().get(e.getFirstRow() - offset).getDate();
                dataModel.setValueAt((oldDate.get(Calendar.MONTH) + 1 + "/" + oldDate.get(Calendar.DAY_OF_MONTH) + "/" + (oldDate.get(Calendar.YEAR))), e.getFirstRow(), 2);
            }
        }
        else if (e.getColumn() == 3){
            int hours = (int) dataModel.getValueAt(e.getFirstRow(), 3);
            if(hours > 0 && hours < 13){
                account.getEntries().get(e.getFirstRow() - offset).setHours(hours);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Hour value is not in accepted range (1 - 12)", "Error", JOptionPane.ERROR_MESSAGE);
                dataModel.setValueAt(account.getEntries().get(e.getFirstRow() - offset).getHours(), e.getFirstRow(), 3);//TODO fix
            }
        }
    }
    
    private boolean parseDate(String s){
        Pattern datePattern = Pattern.compile("^\\d{1,2}/\\d{1,2}/(\\d\\d){1,2}$");
        if(s.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter a date.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(!datePattern.matcher(s).find()){ //TODO convert date
            JOptionPane.showMessageDialog(rootPane, "Please enter a date in the format MM/DD/YYYY.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else{
            Calendar date = new GregorianCalendar();
            boolean acceptable = true; //(acceptable)
            String reason = ""; //Reason for rejection
            final String DNE = "That date does not exist.";
            String[] datePieces = s.split("/"); //Split the date into 3 pieces.
            if(datePieces[2].length() == 2){ //shorthand date form
                datePieces[2] = ("" + date.get(Calendar.YEAR)).substring(0, 2) + datePieces[2]; //Getting the first two digits of the year. This method ensures working code after 2100
            }
            int[] dateNumbers = new int[3];
            for(int i = 0; i < 3; i++){
                dateNumbers[i] = Integer.parseInt(datePieces[i]); //Store the integer values
                if(dateNumbers[i] < 0){ //If they have negative pieces
                    acceptable = false; //UNACCEPTABLE
                    reason = "You cannot have negative numbers in the date.";
                }
            }
            if(Math.abs(dateNumbers[2] - date.get(Calendar.YEAR)) > 1){ //Dates that are < +- 1 year from the current date
                acceptable = false; //UNACCEPTABLE
                reason = "That date is out of the accepted range (1 year).";
            }
            if(dateNumbers[1] > 31){ //Months with more than 31 days
               acceptable = false; //UNACCEPTABLE 
               reason = DNE;
            }
            else if(dateNumbers[0] % 2 == 1 && dateNumbers[1] > 30){ //Short months with more than 30 days
                acceptable = false; //UNACCEPTABLE
                reason = DNE;
            }
            else if(dateNumbers[0] == 2 && dateNumbers[1] > 29){ //February with more than 29 days
                acceptable = false; //UNACCEPTABLE
                reason = DNE;
            }
            else if(dateNumbers[0] == 2 && dateNumbers[1] == 29){ //It's February 29. Leap year detection.
                if(dateNumbers[2] % 4 != 0){ //Year is not divisible by 4; not a leap year
                    acceptable = false; //UNACCEPTABLE
                    reason = DNE;
                }
                else if(dateNumbers[2] % 100 != 0){ //Year is not divisible by 100 (every 100 years, the leap year is skipped)
                    acceptable = true; //(acceptable)
                }
                else if(dateNumbers[2] % 400 != 0){ //Year is not divisible by 400 (Of course, the skipping gets skipped every 400 years)
                    acceptable = false; //UNACCEPTABLE
                    reason = DNE;
                }
                else{ //No reason to think it's not a leap year.
                    acceptable = true; //(acceptable)
                }
            }
            if(acceptable){
                date.set(Integer.parseInt(datePieces[2]), Integer.parseInt(datePieces[0]) - 1, Integer.parseInt(datePieces[1]));
                if(Calendar.getInstance().compareTo(date) < 0){ //Trying to enter dates in the future
                    JOptionPane.showMessageDialog(rootPane, "You cannot enter dates in the future.", "Error", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                else{
                    return true;
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, reason + "\nPlease enter a valid date.", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
    }
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        boolean delete = false, itemsToDelete = false;
        String message = "Are you sure you want to delete the selected entries?\nThis cannot be undone!";
        
        for(int i = dataModel.getRowCount() - 1; i > -1; i--){
            if((boolean)dataModel.getValueAt(i, 0)){
                if(!itemsToDelete){
                    delete = (JOptionPane.showConfirmDialog(rootPane, message, "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)) == 0;
                    itemsToDelete = true;
                }
                if(delete){
                    System.out.println("Deleting hour # " + dataModel.getValueAt(i, 3));
                    String name = (String) dataModel.getValueAt(i, 1);
                    int offset = 0;
                    for(Account a : Run.getAccountList()){
                      if(name.equals(a.getAccountName().replace("+", " "))){
                         account = a;
                         break;
                       }
                      else{
                          offset += a.getEntries().size();
                      }
                   }
                    account.getEntries().remove(i - offset);
                    dataModel.removeRow(i);
                }
                else{
                    dataModel.setValueAt(false, i, 0);
                }
            }
        }
        if(!itemsToDelete){
            JOptionPane.showMessageDialog(rootPane, "There are no entries selected.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            ImportExport.exportAll();
        }
        entryTable.clearSelection();
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(firstNameField.getText().equals("")){
            firstNameField.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }
        if(lastNameField.getText().equals("")){
            lastNameField.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }
        if(Arrays.equals(passwordField.getPassword(), new char[0])){
            passwordField.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }
        if(Arrays.equals(passwordConfirmField.getPassword(), new char[0])){
            passwordConfirmField.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }
        
        
        /*if(parseDate(manualDateEntry.getText())){
            Calendar date = new GregorianCalendar();
            String[] datePieces = manualDateEntry.getText().split("/"); //Split the date into 3 pieces.
            Object[] data = new Object[4];
            data[3] = (date.get(Calendar.MONTH) + 1 + "/" + date.get(Calendar.DAY_OF_MONTH) + "/" + (date.get(Calendar.YEAR)));

            if(datePieces[2].length() == 2){ //shorthand date form
                datePieces[2] = ("" + date.get(Calendar.YEAR)).substring(0, 2) + datePieces[2]; //Getting the first two digits of the year. This method ensures working code after 2100
            }

            date.set(Integer.parseInt(datePieces[2]), Integer.parseInt(datePieces[0]) - 1, Integer.parseInt(datePieces[1]));

            account.addEntry(new Entry(account, (int)hourSelector.getValue(), date));

            data[0] = false;
            data[1] = (date.get(Calendar.MONTH) + 1 + "/" + date.get(Calendar.DAY_OF_MONTH) + "/" + (date.get(Calendar.YEAR)));
            data[2] = (int)hourSelector.getValue();
            dataModel.addRow(data);

            System.out.println("New entry added."); //TODO Auto update table
            System.out.println("Last entry in the list:");
            System.out.println(account.getEntries().get(account.getEntries().size() - 1));
            System.out.println("Now exporting the file:");
            ImportExport.exportAll();

            manualDateEntry.setBorder(defaultBorder);
            JOptionPane.showMessageDialog(rootPane, "Added successfully!", "Success!", JOptionPane.INFORMATION_MESSAGE);
            newBackButtonActionPerformed(evt);
        }
        else{
            manualDateEntry.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        }*/
    }//GEN-LAST:event_submitButtonActionPerformed

    private void newBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBackButtonActionPerformed
        firstNameField.setText("");
        lastNameField.setText("");
        passwordField.setText("");
        passwordConfirmField.setText("");
        firstNameField.setBorder(defaultBorder);
        lastNameField.setBorder(defaultBorder);
        passwordField.setBorder(defaultBorder);
        passwordConfirmField.setBorder(defaultBorder);
        ((CardLayout)(mainPanel.getLayout())).show(mainPanel, "startPanel");
    }//GEN-LAST:event_newBackButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable entryTable;
    private javax.swing.JScrollPane entryTableHeader;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newBackButton;
    private javax.swing.JButton newButton;
    private javax.swing.JPanel newUserPanel;
    private javax.swing.JPasswordField passwordConfirmField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton tableBackButton;
    private javax.swing.JButton viewButton;
    private javax.swing.JPanel viewEditPanel;
    // End of variables declaration//GEN-END:variables
}
